### ISSUE TITLE
Duralumin missing dependency

### ISSUE THREAD

**Issue by Blykam** [pyanodon/pyhightech#14]
"crash-site-assembling-machine-1-repaired" has duralumin as result, but it is not included in this mod.
Duralumin is only included trough Py Raw Ores, but that is not a dependency of Py High Tech resulting in an error.
Please remove duralumin from the results of this item or make Py Raw Ores a dependency.

**Comment by sparr** [comment]
I do not think this is fixed. As of today with current versions on the mod portal, the error persists. Also https://github.com/pyanodon/pyhightech/blob/master/info.json still does not list pyrawores as a dependency

**Comment by kingarthur91** [comment]
its not supposed to have pyrawores as a dependancy and given that we havent posted any updates in 10 months to pyhightech of course its still going to have the error. this issue was fixed back in june. https://github.com/pyanodon/pyhightech/commit/32967ab1de111dc2f23dc70a39e12e61a4c9be52
