### ISSUE TITLE
Nitrobenzene Recipe Bug

### ISSUE THREAD

**Issue by Blykam** [pyanodon/pyhightech#17]
Nitrobenzene is needed for kevlar production. It was uncraftable for me, so I investigated and found out that the recipe was disabled in the mod files. I enabled it and it worked... but just in some worlds. (I now know that it is a dirty fix and does not fix the real problem) I do not know if you (the developers) are aware of this or could help me out. 
Are recipes saved per world/save? I cannot find a reason for this error and cannot fix it. 
It hinders my progress and I do not want to play without this great mod

**Comment by kingarthur91** [comment]
not a py issue
